#!/bin/bash

echo "Running pre-commit hook" 
checks=('setDevelopmentMode\(true)') # create an array

git diff --cached --name-status | while read flag file; do
    if [ "$flag" == 'D' ]; then continue; fi
    for word in ${checks[@]}
    do
        if egrep -q "$word" "$file"; then
            echo "ERROR: Disallowed expression \"${word}\" in file: 
${file}" >&2
            exit 1
        fi
    done
done

